Map progression #34
hsven/mystic-militia pull request #35
Opened 2023-06-09 18:59 UTC by guidzo99

Created the Level tree scene, SampleSceneMap, where I implemented a random tree generator that allow the +çayer to choose his own path on a run with the possibility to restart a run.

2023-06-09 19:00 UTC, guidzo99 commented
closes #33

2023-06-10 09:57 UTC, hsven requested changes
Hard to review on a per-file basis when there's this many changed files haha.
That said, please review again if there's unnecessary files, and delete them.
From what I've seen at a glance, there is still the outdated scene `MapProgression`, that does not use randomized graph maps. and assets such as `Assets/MM6-removebg-preview (1).png` and the `Symbols` folder.

Preferably also try to better organize the folders. For example, in the `Scripts` folder, every script that isn't ours, such as I assume `Assets/Scripts/DottedLineRenderer.cs` and `Assets/Scripts/Point.cs`, should be put into a subfolder of the Scripts folder, with a name that specifies what these are for.

2023-06-10 14:27 UTC, hsven requested changes
I'd like to ask you to move the "Back" button that you added in the battle scene out of the `SquadCreate` object and into the `UI` object, in the hierarchy. Also give it a name so it's easier to know what button this `Button` object is.
![image](https://github.com/hsven/mystic-militia/assets/72400318/c721a08c-be91-42da-bdcb-3678529e3b16)

2023-06-10 14:27 UTC, hsven commented on Assets/MM6-removebg-preview (1).png
Is this file necessary? You may have forgotten to remove this one.

2023-06-10 14:27 UTC, hsven commented on Assets/GotikaOrnament_PERSONAL_USE_ONLY.otf
This font probably should go into the Fonts folder.

2023-06-10 14:27 UTC, hsven commented on Assets/panel_beige.png
Is this a duplicated file? Because I see the exact same file in `Assets/Sprites/Kenney RPG Pack panels/panel_beige.png`

2023-06-10 14:27 UTC, hsven commented on Assets/Scripts/MapPlayerTracker.cs
> +            SceneManager.LoadScene("SampleSceneMap");
The Back button is triggered when the game is paused, i.e. `timeScale = 0`.
As such, returning to the map leads to a paused map.

Simply add the following line directly below this one, and it should be fixed.
`Time.timeScale = 1.0f;`

2023-06-10 14:28 UTC, hsven approved these changes
Missclicked in the previous review, should have approved since I assume that the upcoming changes are small and won't require another review.

2023-06-10 15:46 UTC, merged